"""Export the completed simulation as a self-contained geographic replay."""
import json
from pathlib import Path
from typing import List

VALLEY_COLORS = ["#237A57", "#C76D28", "#6B5B95", "#B33A3A"]

_TEMPLATE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fire Island replay</title><style>
:root{--ink:#20231f;--muted:#687069;--line:#d7d5cd;--paper:#f2f0e8;--panel:#fff;--sea:#e7f1f3;--path:#987b55;--canoe:#4f91a7}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,"Times New Roman",serif}button,select,input{font:inherit}
header{padding:18px 24px 12px;background:var(--panel);border-bottom:1px solid var(--line)}h1{margin:0;font-size:24px;letter-spacing:0}header p{margin:4px 0 0;color:var(--muted);font-size:13px}
.controls{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:10px;padding:10px 24px;background:rgba(255,255,255,.97);border-bottom:1px solid var(--line)}.icon{width:36px;height:34px;border:1px solid var(--line);background:white;cursor:pointer}.controls input{flex:1}.time{min-width:145px;text-align:right;font:13px Consolas,monospace}
.shell{max-width:1180px;margin:auto;padding:16px}.top{display:grid;grid-template-columns:680px 1fr;gap:16px}.panel{background:var(--panel);border:1px solid var(--line);padding:12px}.panel h2{font-size:14px;text-transform:uppercase;letter-spacing:.07em;margin:0 0 10px}
.map{position:relative;width:640px;height:480px;margin:auto;background:radial-gradient(circle at center,#efe6d4 0 16%,transparent 17%),var(--sea);overflow:hidden}.routes{position:absolute;inset:0;width:100%;height:100%}.path{stroke:var(--path);stroke-width:3}.canoe{stroke:var(--canoe);stroke-width:2;stroke-dasharray:7 6}.event-route{stroke:#c02f2f;stroke-width:5;stroke-linecap:round;opacity:.85}.event-route.canoe-event{stroke:#167b9c;stroke-dasharray:8 5}
.volcano{position:absolute;left:264px;top:188px;width:112px;height:104px;text-align:center;padding-top:20px;font-size:43px}.volcano small{display:block;font:12px Georgia;color:#743c26}.valley{position:absolute;width:210px;height:132px;padding:10px;border:3px solid var(--color);background:rgba(255,255,255,.94);box-shadow:0 2px 7px #46544a24}.v0{left:215px;top:14px}.v1{right:14px;top:174px}.v2{left:215px;bottom:14px}.v3{left:14px;top:174px}.valley h3{font-size:15px;margin:0 0 6px;display:flex;justify-content:space-between}.badge{font-size:20px;min-width:26px}.line{display:flex;justify-content:space-between;font:12px/1.45 Consolas,monospace}.bars{display:grid;grid-template-columns:36px 1fr;gap:3px 6px;margin-top:4px;font:10px Consolas,monospace}.bar{height:7px;background:#e6e5df;overflow:hidden}.bar i{display:block;height:100%}.tribes{margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font:10px Consolas,monospace;color:var(--muted)}
.legend{display:flex;gap:14px;flex-wrap:wrap;margin-top:8px;color:var(--muted);font-size:11px}.events{height:408px;overflow:auto;font:12px/1.35 Consolas,monospace}.event{padding:6px;border-bottom:1px solid #eee;cursor:pointer}.event:hover,.event.current{background:#f5e9bd}.empty{color:var(--muted)}
.charts{margin-top:16px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.chart{min-width:0}.chart svg{display:block;width:100%;height:210px}.chart-legend{display:flex;gap:8px;flex-wrap:wrap;font:10px Consolas,monospace;color:var(--muted)}.key{display:inline-flex;align-items:center;gap:3px}.sw{width:12px;height:3px;display:inline-block}.meta{margin-top:12px}.meta summary{cursor:pointer;color:var(--muted);font-size:12px}.meta pre{font:10px Consolas,monospace;white-space:pre-wrap;max-height:180px;overflow:auto}
@media(max-width:900px){.shell{padding:8px}.top{display:block}.top>.panel:first-child{overflow-x:auto}.map{transform-origin:top left}.events{height:220px}.charts{display:flex;overflow-x:auto}.chart{min-width:340px}.controls{padding:8px}.time{min-width:100px}.controls select{max-width:74px}}
</style></head><body>
<header><h1>Fire Island</h1><p>Four valleys, one volcano, shifting families and a recessive blue-eye marker.</p></header>
<div class="controls"><button class="icon" id="play" title="Play">&#9654;</button><input id="slider" type="range" min="0" value="0"><select id="speed" title="Playback speed"><option value="650">0.5x</option><option value="320" selected>1x</option><option value="120">3x</option></select><span class="time" id="time"></span></div>
<div class="shell"><div class="top"><section class="panel"><h2>Island</h2><div class="map" id="map"><svg class="routes" viewBox="0 0 640 480"><line class="path" x1="320" y1="80" x2="550" y2="240"/><line class="path" x1="550" y1="240" x2="320" y2="410"/><line class="path" x1="320" y1="410" x2="90" y2="240"/><line class="path" x1="90" y1="240" x2="320" y2="80"/><line class="canoe" x1="320" y1="80" x2="320" y2="410"/><line class="canoe" x1="90" y1="240" x2="550" y2="240"/><g id="eventRoutes"></g></svg><div class="volcano">🌋<small>central volcano</small></div><div id="valleys"></div></div><div class="legend"><span>solid: mountain path</span><span>dashed: canoe route</span><span>genetics: BB / Bb / bb</span><span>events show for selected turn</span></div></section><aside class="panel"><h2>Event log</h2><div class="events" id="events"></div></aside></div><section class="charts" id="charts"></section><details class="meta"><summary>Run provenance</summary><pre id="meta"></pre></details></div>
<script>
const DATA=__DATA__,COLORS=__COLORS__,history=DATA.history,events=DATA.events,names=DATA.valleyOrder;
const POS=[[320,80],[550,240],[320,410],[90,240]],ICONS={eruption:'🌋',war:'⚔️',migration:'🚶',storm:'⛈️',refugees:'🧳',mixed_families:'🤝',secession:'🏳️'};
const slider=document.getElementById('slider'),time=document.getElementById('time'),valleyRoot=document.getElementById('valleys');slider.max=history.length-1;document.getElementById('meta').textContent=JSON.stringify(DATA.provenance,null,2);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function pct(v){return Math.round(v*100)}
const eventRows=[];if(!events.length)document.getElementById('events').innerHTML='<div class="empty">No events</div>';events.forEach(ev=>{const row=document.createElement('div');row.className='event';const movement=ev.from?`${ev.from} → ${ev.to}`:(ev.valley||'');const amount=ev.count??ev.lost??ev.children??ev.refugees??ev.deaths??'';row.textContent=`${ICONS[ev.type]||'•'} y${ev.year} ${ev.type.replace('_',' ')} ${movement} ${amount}`;row.onclick=()=>{slider.value=ev.turn;render(ev.turn)};document.getElementById('events').appendChild(row);eventRows.push([ev.turn,row])});
function bars(v){const total=Math.max(v.population,1);return `<div class="bars"><span>genes</span><div class="bar"><i style="width:${v.n_BB/total*100}%;background:#7a4b2a;float:left"></i><i style="width:${v.n_Bb/total*100}%;background:#d9a05b;float:left"></i><i style="width:${v.n_bb/total*100}%;background:#2e75b6;float:left"></i></div><span>food</span><div class="bar"><i style="width:${Math.min(v.food_security,1)*100}%;background:#3d8f55"></i></div><span>land</span><div class="bar"><i style="width:${v.land_health*100}%;background:#81734c"></i></div></div>`}
function eventBadge(turn,name){return [...new Set(events.filter(e=>e.turn===turn&&(e.valley===name||e.from===name||e.to===name)).map(e=>ICONS[e.type]||''))].join('')}
function renderRoutes(turn){const root=document.getElementById('eventRoutes');root.innerHTML='';const seen=new Set();events.filter(e=>e.turn===turn&&e.from&&e.to).forEach(e=>{const a=names.indexOf(e.from),b=names.indexOf(e.to),key=[Math.min(a,b),Math.max(a,b),e.route].join(':');if(a<0||b<0||seen.has(key))return;seen.add(key);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',POS[a][0]);line.setAttribute('y1',POS[a][1]);line.setAttribute('x2',POS[b][0]);line.setAttribute('y2',POS[b][1]);line.setAttribute('class','event-route '+(e.route==='canoe'?'canoe-event':''));root.appendChild(line)})}
function render(i){const s=history[i];time.textContent=`turn ${s.turn} · year ${s.year}`;valleyRoot.innerHTML=s.valleys.map((v,j)=>`<article class="valley v${j}" style="--color:${COLORS[j]}"><h3><span>${esc(v.name)}</span><span class="badge">${eventBadge(s.turn,v.name)}</span></h3><div class="line"><span>population</span><b>${v.population}</b></div><div class="line"><span>blue allele q</span><b>${v.q===null?'n/a':v.q.toFixed(3)}</b></div><div class="line"><span>food / land</span><b>${pct(v.food_security)}% / ${pct(v.land_health)}%</b></div>${bars(v)}<div class="tribes">${esc(Object.entries(v.tribes).map(([k,n])=>`${k} ${n}`).join(' · '))}</div></article>`).join('');renderRoutes(s.turn);eventRows.forEach(([turn,row])=>row.classList.toggle('current',turn===s.turn));document.querySelectorAll('.marker').forEach(m=>{m.setAttribute('x1',chartX(i));m.setAttribute('x2',chartX(i))})}
const CW=350,CH=180,L=35,R=8,T=12,B=22;function chartX(i){return L+i/Math.max(history.length-1,1)*(CW-L-R)}function makeChart(title,series,yMax,format,extras=[]){const wrap=document.createElement('section');wrap.className='panel chart';wrap.innerHTML=`<h2>${title}</h2><svg viewBox="0 0 ${CW} ${CH}"></svg><div class="chart-legend"></div>`;const svg=wrap.querySelector('svg');for(let n=0;n<=4;n++){const y=T+n*(CH-T-B)/4;svg.innerHTML+=`<line x1="${L}" y1="${y}" x2="${CW-R}" y2="${y}" stroke="#e5e3dc"/><text x="2" y="${y+3}" font-size="9">${format(yMax*(1-n/4))}</text>`}series.forEach((values,j)=>{const points=values.map((v,i)=>`${chartX(i)},${T+(1-v/yMax)*(CH-T-B)}`).join(' ');svg.innerHTML+=`<polyline points="${points}" fill="none" stroke="${COLORS[j]}" stroke-width="2"/>`});extras.forEach((extra,k)=>{const points=extra.values.map((v,i)=>`${chartX(i)},${T+(1-v/yMax)*(CH-T-B)}`).join(' ');svg.innerHTML+=`<polyline points="${points}" fill="none" stroke="${extra.color}" stroke-width="1.5" stroke-dasharray="5 3"/>`});const marker=document.createElementNS('http://www.w3.org/2000/svg','line');marker.setAttribute('class','marker');marker.setAttribute('y1',T);marker.setAttribute('y2',CH-B);marker.setAttribute('stroke','#222');svg.appendChild(marker);wrap.querySelector('.chart-legend').innerHTML=names.map((n,j)=>`<span class="key"><i class="sw" style="background:${COLORS[j]}"></i>${n}</span>`).join('')+extras.map(e=>`<span class="key"><i class="sw" style="background:${e.color}"></i>${e.name}</span>`).join('');return wrap}
const qSeries=names.map((_,j)=>history.map(s=>s.valleys[j].q??0)),popSeries=names.map((_,j)=>history.map(s=>s.valleys[j].population)),foodSeries=names.map((_,j)=>history.map(s=>s.valleys[j].food_security));const maxPop=Math.max(...popSeries.flat(),1);const meanLand=history.map(s=>s.valleys.reduce((a,v)=>a+v.land_health,0)/s.valleys.length);document.getElementById('charts').append(makeChart('Blue-allele frequency',qSeries,1,v=>Math.round(v*100)+'%'),makeChart('Population',popSeries,maxPop,v=>Math.round(v)),makeChart('Food security / mean land',foodSeries,1.2,v=>Math.round(v*100)+'%',[{name:'mean land',color:'#222',values:meanLand}]));
let timer=null;const play=document.getElementById('play'),speed=document.getElementById('speed');function stop(){clearInterval(timer);timer=null;play.innerHTML='&#9654;'}play.onclick=()=>{if(timer){stop();return}play.innerHTML='&#10074;&#10074;';timer=setInterval(()=>{slider.value=(+slider.value+1)%history.length;render(+slider.value)},+speed.value)};speed.onchange=()=>{if(timer){stop();play.click()}};slider.oninput=()=>render(+slider.value);render(0);
</script></body></html>"""


def export_history_html(history: List[dict], event_log: List[dict], valley_order: List[str],
                        provenance: dict, path: str = "island_replay.html") -> str:
    data = {"history": history, "events": event_log, "valleyOrder": valley_order,
            "provenance": provenance}
    html = _TEMPLATE.replace("__DATA__", json.dumps(data)).replace(
        "__COLORS__", json.dumps(VALLEY_COLORS))
    output = Path(path)
    output.write_text(html, encoding="utf-8")
    return str(output.resolve())